Log entry filtering
Project-4AHIF-JP-FG-BH-TF/node-backend pull request #13
Opened 2024-01-08 12:49 UTC by benni043

this pr adds

1. filtering by ip
2. filtering by date
3. filtering by text
4. filtering by regex
5. filtering by classification

2024-01-08 12:58 UTC, xFizzar approved these changes
looks good to me

2024-01-08 13:12 UTC, JonasPfeifer05 requested changes
please change

2024-01-08 13:12 UTC, JonasPfeifer05 commented on src/entry/logEntry.service.ts
> +      }
create type Filters with those values as instance variables. No need to assign them to individual varaibles

2024-01-08 13:12 UTC, JonasPfeifer05 commented on src/entry/logEntry.service.ts
> +        date,
```suggestion
        filters
```

2024-01-08 13:12 UTC, JonasPfeifer05 commented on src/entry/logEntry.store.ts
> +      if (ip) {
```suggestion
      if (filters.ip) {
```

2024-01-08 13:12 UTC, JonasPfeifer05 commented on src/entry/logEntry.store.ts
> +      if (text) {
```suggestion
      if (filters.text) {
```

2024-01-08 13:12 UTC, JonasPfeifer05 commented on src/entry/logEntry.store.ts
> +      if (regex) {
```suggestion
      if (filters.regex) {
```

2024-01-08 13:12 UTC, JonasPfeifer05 commented on src/entry/logEntry.store.ts
> +      if (classification) {
```suggestion
      if (filters.classification) {
```

2024-01-08 13:12 UTC, JonasPfeifer05 commented on src/entry/logEntry.store.ts
> +      if (date) {
```suggestion
      if (filters.date) {
```

2024-01-08 13:12 UTC, JonasPfeifer05 commented on src/entry/logEntry.store.ts
> +        queryParams.push(date.from);
make it so that from can be null

2024-01-08 13:12 UTC, JonasPfeifer05 commented on src/entry/logEntry.store.ts
> +        } AND $${queryParams.length}`;
If one is missing make it only to check if the date is < or >

2024-01-08 13:12 UTC, JonasPfeifer05 commented on src/entry/logEntry.store.ts
>      sortingOrderDESC: boolean,
```suggestion
    order: "DESC" | "ASC",
```

2024-01-08 13:12 UTC, JonasPfeifer05 commented on src/entry/logEntry.ts
> +};
make this into a "Filter" type

2024-01-08 13:12 UTC, JonasPfeifer05 commented on src/entry/logEntry.store.ts
> +    date: RangeDate | undefined,
```suggestion
    filters: Filters
```

2024-01-08 13:12 UTC, JonasPfeifer05 commented on src/entry/logEntry.store.ts
>        const order = sortingOrderDESC ? "DESC" : "ASC";
```suggestion

```

2024-01-08 13:12 UTC, JonasPfeifer05 commented on src/entry/logEntry.ts
> +};
should also have boolean "isRegex" and one field to pass either the text or regex

2024-01-08 13:12 UTC, JonasPfeifer05 commented on src/entry/logEntry.ts
> +  from: Date;
```suggestion
  from: Date | null;
```

2024-01-09 10:36 UTC, JonasPfeifer05 requested changes

2024-01-09 10:36 UTC, JonasPfeifer05 commented on src/entry/logEntry.service.ts
>        if (from < 0 || count < 0) {
```suggestion
      if (from < 0 || count <= 0) {
```

2024-01-09 10:36 UTC, JonasPfeifer05 commented on src/entry/logEntry.service.ts
>          typeof sortingOrderDESC !== "undefined"
```suggestion
        typeof sortingOrderDESC !== "undefined" &&
        sortingOrderDESC !== "ASC" &&
        sortingOrderDESC !== "DESC"
```

2024-01-09 10:36 UTC, JonasPfeifer05 commented on src/entry/logEntry.store.ts
> +        queryString += "AND service_ip = $" + queryParams.length;
```suggestion
      if (logEntryRequestData.filters?.classification) {
        queryParams.push(logEntryRequestData.filters.classification);
        queryString += "AND classification = $" + queryParams.length;
```

2024-01-09 10:40 UTC, JonasPfeifer05 approved these changes
ok

2024-01-09 10:41 UTC, merged